// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aznlrdrfewhberkrigaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6bmxyZHJmZXdoYmVya3JpZ2FmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwODIxOTgsImV4cCI6MjA2MDY1ODE5OH0.dExkonM8Uoy6rRKFHViNpxjE6DT41BxaMS08qG2MNCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);